[package]
name = "lcd-metrics"
version = "0.1.0"
edition = "2021"

[lib]
name = "lcd_metrics"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["extension-module", "abi3-py37"] }
arrow = "49.0.0"
parquet = "49.0.0"
chrono = "0.4" 